version: '3'
services:
  # db: This doesn't change yet, but it will
  #   image: postgres
  web:
    image: django-docker
    command: bash -c '/code/start_gunicorn.sh'
    env_file: ./config/production.env
    # ports:
    #   - "8000:8000"
    # depends_on: This doesn't change yet.
    #   - db
