version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    # image: global2alex/polar-bears
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./my_app_test:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: ./config/local.env
