version: '3'
services:
 db:
   image: postgres
 web:
   image: django-docker
   command: bash -c '/code/start_gunicorn.sh'
   ports:
     - "8000:8000"
   depends_on:
     - db
   env_file: local.env
